import os
import re
import pandas as pd
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.pdfgen import canvas
from PyPDF2 import PdfMerger, PdfReader, PdfWriter

# ===================== CONFIG =====================
PROCEDURE_DIR = r"D:/CESL/CMMS Issues/Refined/Procedure_PDFs"
WORKPACK_DIR = r"D:/CESL/CMMS Issues/Refined/Work_Packs"
MAINTENANCE_DIR = r"D:/CESL/CMMS Issues/Refined/Maintenance_Schedule"
# ==================================================

os.makedirs(WORKPACK_DIR, exist_ok=True)

# -------------------- HELPERS --------------------
def sanitize_filename(name):
    return re.sub(r'[\\/*?:"<>|]', "_", str(name))


def create_wo_summary_pdf(row, temp_pdf):
    styles = getSampleStyleSheet()

    title = ParagraphStyle(
        "Title",
        parent=styles["Title"],
        spaceAfter=12
    )

    # Footer function to add text on every page
    def add_footer(canvas_obj, doc):
        footer_text = "Generated by Zico’s Maintenance Automation Tool"
        canvas_obj.setFont("Helvetica-Oblique", 8)
        canvas_obj.setFillGray(0.5)
        canvas_obj.drawRightString(A4[0] - 20 * mm, 15 * mm, footer_text)

    doc = SimpleDocTemplate(
        temp_pdf,
        pagesize=A4,
        leftMargin=20 * mm,
        rightMargin=20 * mm,
        topMargin=25 * mm,
        bottomMargin=20 * mm
    )

    story = []
    story.append(Paragraph(row["WO NUMBER"], title))
    story.append(Spacer(1, 10))

    table_data = [
        ["PM NO", row["PM NO"]],
        ["OBJECT ID", row["OBJECT ID"]],
        ["OBJECT DESCRIPTION", row["OBJECT DESCRIPTION"]],
        ["WORK DESCRIPTION", row["WORK DESCRIPTION"]],
        ["WORK TYPE", row["WORK TYPE"]],
        ["DEPARTMENT", row["DEPT RESPONSIBLE"]],
        ["FREQUENCY", row["FREQUENCY"]],
        ["PERIOD", row["PERIOD"]],
        ["PLANNED DUE DATE", str(row["PLANNED DUE DATE"])],
    ]

    table = Table(table_data, colWidths=[60 * mm, 100 * mm])
    story.append(table)

    doc.build(story, onFirstPage=add_footer, onLaterPages=add_footer)


def create_watermark(watermark_text, watermark_file):
    """
    Creates a subtle, professional watermark PDF for A4 pages
    """
    c = canvas.Canvas(watermark_file, pagesize=A4)
    c.setFont("Helvetica-Bold", 40)
    c.setFillGray(0.9, 0.3)  # Light gray, slightly transparent
    c.saveState()
    c.translate(300, 400)  # roughly center
    c.rotate(45)  # diagonal
    c.drawCentredString(0, 0, watermark_text)
    c.restoreState()
    c.save()


def add_watermark(input_pdf, watermark_pdf, output_pdf):
    """
    Applies watermark behind the content of all pages
    """
    reader = PdfReader(input_pdf)
    watermark = PdfReader(watermark_pdf).pages[0]
    writer = PdfWriter()

    for page in reader.pages:
        page.merge_page(watermark)  # watermark behind content
        writer.add_page(page)

    with open(output_pdf, "wb") as f:
        writer.write(f)


# -------------------- MAIN --------------------
def generate_work_packs(maintenance_file):
    df = pd.read_excel(maintenance_file)

    # Create watermark PDF once
    watermark_file = os.path.join(WORKPACK_DIR, "watermark.pdf")
    create_watermark("FPSO TE", watermark_file)

    for _, row in df.iterrows():
        wo_number = sanitize_filename(row["WO NUMBER"])
        procedure_title = sanitize_filename(row["PROCEDURE"])

        procedure_pdf = os.path.join(PROCEDURE_DIR, f"{procedure_title}.pdf")
        if not os.path.exists(procedure_pdf):
            print(f"Procedure not found for WO {wo_number}: {procedure_title}")
            continue

        temp_summary = os.path.join(WORKPACK_DIR, f"{wo_number}_summary.pdf")
        temp_merged = os.path.join(WORKPACK_DIR, f"{wo_number}_merged.pdf")
        output_pdf = os.path.join(WORKPACK_DIR, f"{wo_number}.pdf")

        create_wo_summary_pdf(row, temp_summary)

        # Merge summary + procedure
        merger = PdfMerger()
        merger.append(temp_summary)
        merger.append(procedure_pdf)
        merger.write(temp_merged)
        merger.close()

        # Add watermark
        add_watermark(temp_merged, watermark_file, output_pdf)

        # Clean up temp files
        os.remove(temp_summary)
        os.remove(temp_merged)

        print(f"Work Pack created: {output_pdf}")


# -------------------- EXECUTION --------------------
if __name__ == "__main__":
    maintenance_files = [f for f in os.listdir(MAINTENANCE_DIR) if f.endswith(".xlsx")]
    if not maintenance_files:
        print("No maintenance schedule files found.")
    else:
        latest_file = max(maintenance_files, key=lambda f: os.path.getctime(os.path.join(MAINTENANCE_DIR, f)))
        generate_work_packs(os.path.join(MAINTENANCE_DIR, latest_file))
